# Generated by Django 4.1.7 on 2023-05-15 16:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Your Post Title Here.', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('featured', models.ImageField(blank=True, null=True, upload_to='featured_image/')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
